[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  inputs = {
    disableNextImageOptimizer = false,
    enableAdvancedFormsSupport = true
  }
