[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functionsDir = ".next/serverless"

[functions]
  directory = ".next/serverless"

# Handle calendar API specifically with Netlify function
[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/calendar"
  status = 200
  force = true

# Handle other API routes with Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Handle static files first (images, etc.)
[[redirects]]
  from = "/forgn_v2.png"
  to = "/public/forgn_v2.png"
  status = 200

[[redirects]]
  from = "/forgn_v2_metadata.png"
  to = "/public/forgn_v2_metadata.png"
  status = 200

[[redirects]]
  from = "/daniel.webp"
  to = "/public/daniel.webp"
  status = 200

[[redirects]]
  from = "/activation.jpg"
  to = "/public/activation.jpg"
  status = 200

# Handle image directories
[[redirects]]
  from = "/gallery/*"
  to = "/public/gallery/:splat"
  status = 200

[[redirects]]
  from = "/sculpture/*"
  to = "/public/sculpture/:splat"
  status = 200

[[redirects]]
  from = "/digital/*"
  to = "/public/digital/:splat"
  status = 200

[[redirects]]
  from = "/team/*"
  to = "/public/team/:splat"
  status = 200

[[redirects]]
  from = "/activation/*"
  to = "/public/activation/:splat"
  status = 200

[[redirects]]
  from = "/donate/*"
  to = "/public/donate/:splat"
  status = 200

[[redirects]]
  from = "/incubator/*"
  to = "/public/incubator/:splat"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/public/icons/:splat"
  status = 200

[[redirects]]
  from = "/campaign/*"
  to = "/public/campaign/:splat"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Add headers for static assets
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 